coloredAdMessage: "Colored ad message here"
nonColoredAdMessage: "Non-colored ad message here"
clickForMessage: "&9&lAD &7| &eClick here to copy the ad message."
onlyPlayers: "&cOnly players can execute this command."
checkingRankMessage: "&9&lAD &7| &eChecking your rank..."